In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv("Desktop/imdb_top_1000.csv")

In [4]:
movies = movies[['Series_Title','Overview','Genre','Director','Star1','Star2','Star3','Star4']]
movies

,Series_Title,Overview,Genre,Director,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,Two imprisoned men bond over a number of years...,Drama,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler
1,The Godfather,An organized crime dynasty's aging patriarch t...,"Crime, Drama",Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton
2,The Dark Knight,When the menace known as the Joker wreaks havo...,"Action, Crime, Drama",Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine
3,The Godfather: Part II,The early life and career of Vito Corleone in ...,"Crime, Drama",Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton
4,12 Angry Men,A jury holdout attempts to prevent a miscarria...,"Crime, Drama",Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler
...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,A young New York socialite becomes interested ...,"Comedy, Drama, Romance",Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen
996,Giant,Sprawling epic covering the life of a Texas ca...,"Drama, Western",George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker
997,From Here to Eternity,"In Hawaii in 1941, a private is cruelly punish...","Drama, Romance, War",Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed
998,Lifeboat,Several survivors of a torpedoed merchant ship...,"Drama, War",Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix
999,The 39 Steps,A man in London tries to help a counter-espion...,"Crime, Mystery, Thriller",Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle

In [5]:
movies.dropna(inplace=True)

In [6]:
movies.sample(7)

,Series_Title,Overview,Genre,Director,Star1,Star2,Star3,Star4
760,Flipped,Two eighth-graders start to have feelings for ...,"Comedy, Drama, Romance",Rob Reiner,Madeline Carroll,Callan McAuliffe,Rebecca De Mornay,Anthony Edwards
194,Sherlock Jr.,"A film projectionist longs to be a detective, ...","Action, Comedy, Romance",Buster Keaton,Buster Keaton,Kathryn McGuire,Joe Keaton,Erwin Connelly
528,Hannah and Her Sisters,"Between two Thanksgivings two years apart, Han...","Comedy, Drama",Woody Allen,Mia Farrow,Dianne Wiest,Michael Caine,Barbara Hershey
477,Star Wars: Episode VII - The Force Awakens,"As a new threat to the galaxy rises, Rey, a de...","Action, Adventure, Sci-Fi",J.J. Abrams,Daisy Ridley,John Boyega,Oscar Isaac,Domhnall Gleeson
643,Waking Life,A man shuffles through a dream meeting various...,"Animation, Drama, Fantasy",Richard Linklater,Ethan Hawke,Trevor Jack Brooks,Lorelei Linklater,Wiley Wiggins
537,La montaña sagrada,"In a corrupt, greed-fueled world, a powerful a...","Adventure, Drama, Fantasy",Alejandro Jodorowsky,Alejandro Jodorowsky,Horacio Salinas,Zamira Saunders,Juan Ferrara
659,Tombstone,A successful lawman's plans to retire anonymou...,"Action, Biography, Drama",George P. Cosmatos,Kevin Jarre,Kurt Russell,Val Kilmer,Sam Elliott

In [7]:
movies['Director'] = movies['Director'].apply(lambda x: x.replace(" ", ""))

In [8]:
movies.sample(5)

,Series_Title,Overview,Genre,Director,Star1,Star2,Star3,Star4
810,Shine,"Pianist David Helfgott, driven by his father a...","Biography, Drama, Music",ScottHicks,Geoffrey Rush,Armin Mueller-Stahl,Justin Braine,Sonia Todd
629,Veer-Zaara,"Veer-Zaara is a saga of love, separation, cour...","Drama, Family, Musical",YashChopra,Shah Rukh Khan,Preity Zinta,Rani Mukerji,Kirron Kher
687,The King of Comedy,Rupert Pupkin is a passionate yet unsuccessful...,"Comedy, Crime, Drama",MartinScorsese,Robert De Niro,Jerry Lewis,Diahnne Abbott,Sandra Bernhard
22,Cidade de Deus,"In the slums of Rio, two kids' paths diverge a...","Crime, Drama",FernandoMeirelles,Kátia Lund,Alexandre Rodrigues,Leandro Firmino,Matheus Nachtergaele
25,The Green Mile,The lives of guards on Death Row are affected ...,"Crime, Drama, Fantasy",FrankDarabont,Tom Hanks,Michael Clarke Duncan,David Morse,Bonnie Hunt

In [9]:
movies['Star1'] = movies['Star1'].apply(lambda x: x.replace(" ", ""))
movies['Star2'] = movies['Star2'].apply(lambda x: x.replace(" ", ""))

In [11]:
movies

,Series_Title,Overview,Genre,Director,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,Two imprisoned men bond over a number of years...,Drama,FrankDarabont,TimRobbins,MorganFreeman,BobGunton,WilliamSadler
1,The Godfather,An organized crime dynasty's aging patriarch t...,"Crime, Drama",FrancisFordCoppola,MarlonBrando,AlPacino,JamesCaan,DianeKeaton
2,The Dark Knight,When the menace known as the Joker wreaks havo...,"Action, Crime, Drama",ChristopherNolan,ChristianBale,HeathLedger,AaronEckhart,MichaelCaine
3,The Godfather: Part II,The early life and career of Vito Corleone in ...,"Crime, Drama",FrancisFordCoppola,AlPacino,RobertDeNiro,RobertDuvall,DianeKeaton
4,12 Angry Men,A jury holdout attempts to prevent a miscarria...,"Crime, Drama",SidneyLumet,HenryFonda,LeeJ.Cobb,MartinBalsam,JohnFiedler
...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,A young New York socialite becomes interested ...,"Comedy, Drama, Romance",BlakeEdwards,AudreyHepburn,GeorgePeppard,PatriciaNeal,BuddyEbsen
996,Giant,Sprawling epic covering the life of a Texas ca...,"Drama, Western",GeorgeStevens,ElizabethTaylor,RockHudson,JamesDean,CarrollBaker
997,From Here to Eternity,"In Hawaii in 1941, a private is cruelly punish...","Drama, Romance, War",FredZinnemann,BurtLancaster,MontgomeryClift,DeborahKerr,DonnaReed
998,Lifeboat,Several survivors of a torpedoed merchant ship...,"Drama, War",AlfredHitchcock,TallulahBankhead,JohnHodiak,WalterSlezak,WilliamBendix
999,The 39 Steps,A man in London tries to help a counter-espion...,"Crime, Mystery, Thriller",AlfredHitchcock,RobertDonat,MadeleineCarroll,LucieMannheim,GodfreyTearle

In [10]:
movies['Star3'] = movies['Star3'].apply(lambda x: x.replace(" ", ""))
movies['Star4'] = movies['Star4'].apply(lambda x: x.replace(" ", ""))

In [12]:
movies

,Series_Title,Overview,Genre,Director,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,Two imprisoned men bond over a number of years...,Drama,FrankDarabont,TimRobbins,MorganFreeman,BobGunton,WilliamSadler
1,The Godfather,An organized crime dynasty's aging patriarch t...,"Crime, Drama",FrancisFordCoppola,MarlonBrando,AlPacino,JamesCaan,DianeKeaton
2,The Dark Knight,When the menace known as the Joker wreaks havo...,"Action, Crime, Drama",ChristopherNolan,ChristianBale,HeathLedger,AaronEckhart,MichaelCaine
3,The Godfather: Part II,The early life and career of Vito Corleone in ...,"Crime, Drama",FrancisFordCoppola,AlPacino,RobertDeNiro,RobertDuvall,DianeKeaton
4,12 Angry Men,A jury holdout attempts to prevent a miscarria...,"Crime, Drama",SidneyLumet,HenryFonda,LeeJ.Cobb,MartinBalsam,JohnFiedler
...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,A young New York socialite becomes interested ...,"Comedy, Drama, Romance",BlakeEdwards,AudreyHepburn,GeorgePeppard,PatriciaNeal,BuddyEbsen
996,Giant,Sprawling epic covering the life of a Texas ca...,"Drama, Western",GeorgeStevens,ElizabethTaylor,RockHudson,JamesDean,CarrollBaker
997,From Here to Eternity,"In Hawaii in 1941, a private is cruelly punish...","Drama, Romance, War",FredZinnemann,BurtLancaster,MontgomeryClift,DeborahKerr,DonnaReed
998,Lifeboat,Several survivors of a torpedoed merchant ship...,"Drama, War",AlfredHitchcock,TallulahBankhead,JohnHodiak,WalterSlezak,WilliamBendix
999,The 39 Steps,A man in London tries to help a counter-espion...,"Crime, Mystery, Thriller",AlfredHitchcock,RobertDonat,MadeleineCarroll,LucieMannheim,GodfreyTearle

In [13]:
movies['tags'] = (
    movies['Overview'] + " " +
    movies['Genre'] + " " +
    movies['Director'] + " " +
    movies['Star1'] + " " +
    movies['Star2'] + " " +
    movies['Star3'] + " " +
    movies['Star4']
)

In [37]:
movies.sample(20)

,Series_Title,Overview,Genre,Director,Star1,Star2,Star3,Star4,tags
540,"Aguirre, der Zorn Gottes","In the 16th century, the ruthless and insane D...","Action, Adventure, Biography",WernerHerzog,KlausKinski,RuyGuerra,HelenaRojo,DelNegro,"In the 16th century, the ruthless and insane D..."
305,On the Waterfront,An ex-prize fighter turned longshoreman strugg...,"Crime, Drama, Thriller",EliaKazan,MarlonBrando,KarlMalden,LeeJ.Cobb,RodSteiger,An ex-prize fighter turned longshoreman strugg...
836,After Hours,An ordinary word processor has the worst night...,"Comedy, Crime, Drama",MartinScorsese,GriffinDunne,RosannaArquette,VernaBloom,TommyChong,An ordinary word processor has the worst night...
845,Le locataire,A bureaucrat rents a Paris apartment where he ...,"Drama, Thriller",RomanPolanski,RomanPolanski,IsabelleAdjani,MelvynDouglas,JoVanFleet,A bureaucrat rents a Paris apartment where he ...
216,Rush,The merciless 1970s rivalry between Formula On...,"Action, Biography, Drama",RonHoward,DanielBrühl,ChrisHemsworth,OliviaWilde,AlexandraMariaLara,The merciless 1970s rivalry between Formula On...
774,3:10 to Yuma,A small-time rancher agrees to hold a captured...,"Action, Crime, Drama",JamesMangold,RussellCrowe,ChristianBale,BenFoster,LoganLerman,A small-time rancher agrees to hold a captured...
773,Brokeback Mountain,The story of a forbidden and secretive relatio...,"Drama, Romance",AngLee,JakeGyllenhaal,HeathLedger,MichelleWilliams,RandyQuaid,The story of a forbidden and secretive relatio...
147,The Wolf of Wall Street,"Based on the true story of Jordan Belfort, fro...","Biography, Crime, Drama",MartinScorsese,LeonardoDiCaprio,JonahHill,MargotRobbie,MatthewMcConaughey,"Based on the true story of Jordan Belfort, fro..."
952,The Hurricane,"The story of Rubin 'Hurricane' Carter, a boxer...","Biography, Drama, Sport",NormanJewison,DenzelWashington,VicellousShannon,DeborahKaraUnger,LievSchreiber,"The story of Rubin 'Hurricane' Carter, a boxer..."
239,Salinui chueok,"In a small Korean province in 1986, two detect...","Crime, Drama, Mystery",BongJoonHo,Kang-hoSong,KimSang-kyung,Roe-haKim,Jae-hoSong,"In a small Korean province in 1986, two detect..."
744,The Lego Movie,"An ordinary LEGO construction worker, thought ...","Animation, Action, Adventure",ChristopherMiller,PhilLord,ChrisPratt,WillFerrell,ElizabethBanks,"An ordinary LEGO construction worker, thought ..."
916,The Visitor,A college professor travels to New York City t...,Drama,TomMcCarthy,RichardJenkins,HaazSleiman,DanaiGurira,HiamAbbass,A college professor travels to New York City t...
536,All the President's Men,"""The Washington Post"" reporters Bob Woodward a...","Biography, Drama, History",AlanJ.Pakula,DustinHoffman,RobertRedford,JackWarden,MartinBalsam,"""The Washington Post"" reporters Bob Woodward a..."
897,Philomena,A world-weary political journalist picks up th...,"Biography, Comedy, Drama",StephenFrears,JudiDench,SteveCoogan,SophieKennedyClark,MareWinningham,A world-weary political journalist picks up th...
662,Naked,"Parallel tales of two sexually obsessed men, o...","Comedy, Drama",MikeLeigh,DavidThewlis,LesleySharp,KatrinCartlidge,GregCruttwell,"Parallel tales of two sexually obsessed men, o..."
39,Gladiator,A former Roman General sets out to exact venge...,"Action, Adventure, Drama",RidleyScott,RussellCrowe,JoaquinPhoenix,ConnieNielsen,OliverReed,A former Roman General sets out to exact venge...
78,Dr. Strangelove or: How I Learned to Stop Worr...,An insane general triggers a path to nuclear h...,Comedy,StanleyKubrick,PeterSellers,GeorgeC.Scott,SterlingHayden,KeenanWynn,An insane general triggers a path to nuclear h...
248,The Sixth Sense,A boy who communicates with spirits seeks the ...,"Drama, Mystery, Thriller",M.NightShyamalan,BruceWillis,HaleyJoelOsment,ToniCollette,OliviaWilliams,A boy who communicates with spirits seeks the ...
606,Straight Outta Compton,The rap group NWA emerges from the mean street...,"Biography, Drama, History",F.GaryGray,O'SheaJacksonJr.,CoreyHawkins,JasonMitchell,NeilBrownJr.,The rap group NWA emerges from the mean street...
815,Il postino,A simple Italian postman learns to love poetry...,"Biography, Comedy, Drama",MichaelRadford,MassimoTroisi,MassimoTroisi,PhilippeNoiret,MariaGraziaCucinotta,A simple Italian postman learns to love poetry...

In [16]:
new = movies[['Series_Title','tags']]

In [18]:
new.loc[:, 'tags'] = new['tags'].str.lower()

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')
vectors = cv.fit_transform(new['tags']).toarray()

In [20]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

In [21]:
def recommend(movie):
    movie_index = new[new['Series_Title'] == movie].index[0]
    distances = similarity[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    for i in movies_list:
        print(new.iloc[i[0]].Series_Title)

In [22]:
recommend("The Dark Knight")

Batman Begins
The Dark Knight Rises
Kill Bill: Vol. 1
The Prestige
La battaglia di Algeri

In [23]:
recommend("Iron Man")

The Avengers
Captain America: Civil War
The Fifth Element
Avengers: Infinity War
Predator

In [29]:
recommend("Sholay")

Bajrangi Bhaijaan
Hot Fuzz
Gladiator
The Goonies
Guardians of the Galaxy Vol. 2

In [38]:
recommend("After Hours")

Do lok tin si
Les quatre cents coups
The King of Comedy
The Wolf of Wall Street
The Sting